apiVersion: v1
kind: Service
metadata:
  name: pdf-cms-service
spec:
  selector:
    app: pdf-cms
  type: NodePort        
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8000  # Container port
      nodePort: 30080   # Access via <node-ip>:30080 (30000â€“32767 range)
